### PR TITLE
Modify tab border style error.

### PR DESCRIPTION
**Pull request by chenhbc**

### CODE REVIEW

**Comment by brrd** [comment]
This PR is not really clear but I think I don't agree. IMO `.etabs-tab:first-child` should be hidden. 

Why not: 

```css
.etabs-tab {
     border-left: none;
}
```

**Comment by chenhbc** [comment]
If so, the first TAB of the border will not display.

**Comment by brrd** [comment]
> If so, the first TAB's left border will not display.

Obviously, and this is what we want.

image

versus

image

**Comment by chenhbc** [comment]
Well, that's fine

**Comment by brrd** [comment]
Done: a2761ab1473e522255d7566c26c7ea9c3e1d691a

**Pull request closed without merging**
