### PR TITLE
fixes #59 - hide webviews using visibility style instead of zero size

### LINKED ISSUE #59: Unpredictable behaviour of webviews when tabs are created as inactive
It is a known issue that a webview may behave unusually when it is hidden using "hidden" attribute or using "display: none" style - [official source](https://electronjs.org/docs/api/webview-tag#css-styling-notes)

It turns out it also does not behave nice when being resized in order to be hidden, which is current implementation.

### Reproduction scenario:
1. Create an inactive tab with a valid link to a Youtube video and wait until the contents is loaded. Make sure not to make the tab active until the contents is loaded.
2. Make the tab active.

### Expected behaviour:
1. The contents is sized according to the window size and does not start resizing when the tab is made active.
2. Any Chrome extensions added function properly.

### Observed behaviour:
1. The contents is sized to zero size and start resizing when the tab is made active.
2. Chrome extension content scripts are not injected into the page.
_This behaviour is not observed when the tab is created as active._

[Official documentation](https://electronjs.org/docs/api/webview-tag#css-styling-notes) provides recommendations on which style to use to hide webviews.

### PR DESCRIPTION
**Pull request by maxosprojects**
… official documentation https://electronjs.org/docs/api/webview-tag#css-styling-notes

### CODE REVIEW

**Comment by matheo** [comment]
@maxosprojects this needs a `position: relative;` for `.etabs-views` right? otherwise the view takes the whole screen :) thanks for this!

**Comment by brrd** [comment]
@matheo I'm sorry, I forgot about this one. Anyway I didn't merge it because as explained in #59 I first want to be sure it works on OSX (see discussion #22). Maybe you can confirm that this change is working on OSX as well?

> unfortunately, this lib is not getting too much attention

I'm sorry. This is a non-profit project and I'm doing my best to maintain it on my spare time 😕

**Comment by matheo** [comment]
@brrd sorry about my comment, I'm glad you have this issue tracked. For my app, I'm moving from webview to BrowserView using https://github.com/ChugunovRoman/figma-linux as a base.
Thanks for your time!

**Comment by brrd** [comment]
@inureyes Thank you for your feedback.

Can someone provide a working PR (with `position:relative` added to `.etabs-views`)?

**Comment by brrd** [comment]
@inureyes Thank you

**Pull request closed without merging**
