### PR TITLE
Add TypeScript types

### PR DESCRIPTION
**Pull request by vaskevich**
Adding TS types for this package.

### CODE REVIEW

**Comment by brrd** [comment]
Excuse-me, I'm not familiar with TypeScript. Could you explain why we need this?

**Comment by manndave** [comment]
Typescript is like CoffeeScript - it transpiles down to JS.  typescriptlang.org.  Personally, I'm thrilled that there are TS type definitions - it will make my work *so* much easier.  Anyone using Angular in Electron probably feels the same way.

**Comment by brrd** [comment]
@manndave I know what TypeScript is, but I don't know the purpose of TS types definition in a module which is not written in TypeScript. Maybe you have a link to some concise documentation about this specific question?

**Comment by manndave** [comment]
@brrd - Oh, OK.  I was responding to your comment "I'm not familiar with typescript".  Sorry.

Anyway, the type definitions will basically provide two things:
1. Strong typing, enforced by the transpiler.  If someone tries to, for example, pass a string where a number is expected, they'll get a warning.  The type definition will define the types of each argument expected by a function, each public variable, etc in order to facilitate this.
2. Intellisense - (including the expected types) making the discovery of methods/members much easier, especially for newbies.

The type definitions don't change anything about the core code, they're just a thing sitting off to the side that provide help to anyone using the code from TS.

HTH.

**Comment by brrd** [comment]
@manndave Thank you for this explanation. Now I understand why this is an improvement.

**Pull request merged**
